import {Inter} from 'next/font/google'
import './globals.css'
import SessionContextProvider from "@/contexts/SessionContextProvider";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({children}) => {
    return (
        <html lang="en">
        <SessionContextProvider>
            <body className={inter.className}>{children}</body>
        </SessionContextProvider>
        </html>
    )
}

export default RootLayout;
